* el-job

Imagine you have a function you'd like to run on a long list of inputs.  You could run =(mapcar #'FN INPUTS)=, but that hangs Emacs until done.

This library gives you the tools to split up the inputs and run the function in many subprocesses (one per CPU core), then merges their outputs and passes it back to the current Emacs.  In the meantime, current Emacs does not hang at all.


-------

For real-world usage, search for =el-job-launch= in the source of [[https://github.com/meedstrom/org-node/blob/use-el-job/org-node.el][org-node.el]].


** Limitations

1. Still in a development honeymoon, so argument names are not set in stone.  Check back often!

2. For now, some limitations on FN's return value, which must always be a list of a fixed length, where the elements are themselves lists.  For example, at the end of org-node-parser.el, it returns:

   #+begin_src elisp
       (list (if missing-file (list missing-file))
             (if file-mtime (list file-mtime))
             found-nodes ;; always a list
             org-node-parser--paths-types ;; always a list
             org-node-parser--found-links ;; always a list
             (if problem (list problem))))
   #+end_src

   May seem clunky when you return lists of only one item, but at least it is easy to extend.
